-- T-006a: audit module. Generated by drizzle-kit, then hand-completed where Drizzle cannot
-- express the feature (partitioning, roles, grants, triggers, functions) — see
-- docs/06-engineering/migrations.md. The meta/ snapshot matches the schema.ts definition.
CREATE SCHEMA "audit";
--> statement-breakpoint
CREATE TABLE "audit"."chain_head" (
	"id" integer PRIMARY KEY NOT NULL,
	"seq" bigint NOT NULL,
	"hash" text NOT NULL,
	CONSTRAINT "chain_head_singleton" CHECK ("audit"."chain_head"."id" = 1)
);
--> statement-breakpoint
-- genesis: seq 0, hash = 64 zeros (docs/03-architecture/audit-log.md)
INSERT INTO "audit"."chain_head" ("id", "seq", "hash")
VALUES (1, 0, '0000000000000000000000000000000000000000000000000000000000000000');
--> statement-breakpoint
CREATE TABLE "audit"."events" (
	"id" uuid NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"seq" bigint NOT NULL,
	"actor_type" text NOT NULL,
	"actor_id" text NOT NULL,
	"action" text NOT NULL,
	"entity_type" text,
	"entity_id" text,
	"location_id" uuid,
	"ip_hash" text,
	"ua_hash" text,
	"data" jsonb NOT NULL,
	"prev_hash" text NOT NULL,
	"hash" text NOT NULL,
	CONSTRAINT "events_id_at_pk" PRIMARY KEY("id","at")
) PARTITION BY RANGE ("at");
--> statement-breakpoint
CREATE INDEX "events_seq_idx" ON "audit"."events" USING btree ("seq");--> statement-breakpoint
CREATE INDEX "events_entity_idx" ON "audit"."events" USING btree ("entity_type","entity_id");--> statement-breakpoint
-- Append-only, defence in depth (D-027): grants below are the first line, this trigger the second
-- (grants do not bind the table owner; the trigger does).
CREATE FUNCTION "audit"."reject_mutation"() RETURNS trigger LANGUAGE plpgsql
  SET search_path = pg_catalog, audit AS $$
BEGIN
  RAISE EXCEPTION '% on %.% is not allowed: the audit log is append-only', TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME
    USING ERRCODE = 'insufficient_privilege';
END;
$$;
--> statement-breakpoint
-- row triggers on the partitioned parent are cloned onto every partition
CREATE TRIGGER "events_append_only_rows" BEFORE UPDATE OR DELETE ON "audit"."events"
  FOR EACH ROW EXECUTE FUNCTION "audit"."reject_mutation"();
--> statement-breakpoint
CREATE TRIGGER "events_append_only_truncate" BEFORE TRUNCATE ON "audit"."events"
  FOR EACH STATEMENT EXECUTE FUNCTION "audit"."reject_mutation"();
--> statement-breakpoint
CREATE TRIGGER "chain_head_no_delete" BEFORE DELETE OR TRUNCATE ON "audit"."chain_head"
  FOR EACH STATEMENT EXECUTE FUNCTION "audit"."reject_mutation"();
--> statement-breakpoint
-- Monthly partitions by UTC month (D-029). No DEFAULT partition: an event outside every partition
-- fails closed. Needs DDL rights: run by the migration/maintenance role, never by the app role.
CREATE FUNCTION "audit"."ensure_partitions"(months_ahead integer, from_month timestamptz DEFAULT now()) RETURNS integer LANGUAGE plpgsql
  -- timestamptz month arithmetic runs in the session TimeZone: pin UTC or a Brussels session shifts
  -- the bounds by an hour and the next run creates an overlapping partition (architect R1)
  SET TimeZone = 'UTC' SET search_path = pg_catalog, audit AS $$
DECLARE
  first_month timestamptz := date_trunc('month', from_month AT TIME ZONE 'UTC') AT TIME ZONE 'UTC';
  created integer := 0;
  part_start timestamptz;
  part_end timestamptz;
  part_name text;
BEGIN
  IF months_ahead < 0 OR months_ahead > 24 THEN
    RAISE EXCEPTION 'months_ahead must be between 0 and 24';
  END IF;
  FOR i IN 0..months_ahead LOOP
    part_start := first_month + make_interval(months => i);
    part_end := first_month + make_interval(months => i + 1);
    part_name := format('events_y%sm%s',
      to_char(part_start AT TIME ZONE 'UTC', 'YYYY'), to_char(part_start AT TIME ZONE 'UTC', 'MM'));
    IF to_regclass(format('audit.%I', part_name)) IS NULL THEN
      EXECUTE format('CREATE TABLE audit.%I PARTITION OF audit.events FOR VALUES FROM (%L) TO (%L)',
        part_name, part_start, part_end);
      -- global uniqueness of seq rests on the chain-head lock; this catches a duplicate per partition
      EXECUTE format('CREATE UNIQUE INDEX %I ON audit.%I (seq)', part_name || '_seq_uq', part_name);
      -- statement triggers are not cloned: protect TRUNCATE on the partition itself too
      EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON audit.%I FOR EACH STATEMENT EXECUTE FUNCTION audit.reject_mutation()',
        part_name || '_no_truncate', part_name);
      created := created + 1;
    END IF;
  END LOOP;
  RETURN created;
END;
$$;
--> statement-breakpoint
-- How many whole months AFTER the current one already have a partition (alert when < 2).
CREATE FUNCTION "audit"."future_partitions"() RETURNS integer LANGUAGE sql STABLE
  SET TimeZone = 'UTC' SET search_path = pg_catalog, audit AS $$
  SELECT count(*)::integer
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'audit'
    AND c.relkind = 'r'
    AND c.relname ~ '^events_y[0-9]{4}m[0-9]{2}$'
    AND c.relname > 'events_y' || to_char(now() AT TIME ZONE 'UTC', 'YYYY') || 'm' || to_char(now() AT TIME ZONE 'UTC', 'MM');
$$;
--> statement-breakpoint
DO $$
BEGIN
  -- runtime role (NOLOGIN group); the production login role is mapped to it in B-08 (D-027)
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'igs_app') THEN
    CREATE ROLE "igs_app" NOLOGIN;
  END IF;
END
$$;
--> statement-breakpoint
REVOKE ALL ON SCHEMA "audit" FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON ALL TABLES IN SCHEMA "audit" FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON FUNCTION "audit"."ensure_partitions"(integer, timestamptz) FROM PUBLIC;
--> statement-breakpoint
GRANT USAGE ON SCHEMA "audit" TO "igs_app";
--> statement-breakpoint
-- INSERT + SELECT only on events; the head row is read and advanced, never created or deleted
GRANT SELECT, INSERT ON "audit"."events" TO "igs_app";
--> statement-breakpoint
GRANT SELECT, UPDATE ON "audit"."chain_head" TO "igs_app";
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION "audit"."future_partitions"() TO "igs_app";
--> statement-breakpoint
SELECT "audit"."ensure_partitions"(3);
