-- T-014 (architect R1): audit partition functions must not depend on the session TimeZone.
-- Custom migration (functions are outside Drizzle's schema model); `meta/` was generated by
-- `drizzle-kit generate --custom` and is untouched otherwise (D-016). 0005 stays as applied.
--
-- timestamptz month arithmetic runs in the session TimeZone: under Europe/Brussels the 0005 version
-- put bounds at 01:00 UTC and the next month's run created an OVERLAPPING partition, after which
-- every audited command failed (no DEFAULT partition). Fix: pin TimeZone and search_path on every
-- function, do the month arithmetic on timezone-less timestamps, and convert at the end.

-- 1. Every existing partition must already sit on exact UTC month starts. Pre-production a
--    misaligned database is reset, not repaired (D-018). Kept as a function so it can also be run
--    as a periodic check and tested.
CREATE FUNCTION "audit"."assert_partitions_aligned"() RETURNS integer LANGUAGE plpgsql
  SET TimeZone = 'UTC' SET search_path = pg_catalog, audit AS $$
DECLARE
  part record;
  month_start date;
  expected text;
  checked integer := 0;
BEGIN
  FOR part IN
    SELECT c.relname AS name, pg_get_expr(c.relpartbound, c.oid) AS bound
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'audit' AND c.relkind = 'r' AND c.relname ~ '^events_y[0-9]{4}m[0-9]{2}$'
    ORDER BY c.relname
  LOOP
    -- events_yYYYYmMM
    month_start := make_date(substr(part.name, 9, 4)::integer, substr(part.name, 14, 2)::integer, 1);
    expected := format('FOR VALUES FROM (%L) TO (%L)',
      to_char(month_start, 'YYYY-MM-DD') || ' 00:00:00+00',
      to_char(month_start + interval '1 month', 'YYYY-MM-DD') || ' 00:00:00+00');
    IF part.bound IS DISTINCT FROM expected THEN
      RAISE EXCEPTION 'audit partition % is not aligned to UTC month starts (found %, expected %): reset the database (D-018)',
        part.name, part.bound, expected;
    END IF;
    checked := checked + 1;
  END LOOP;
  RETURN checked;
END;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION "audit"."assert_partitions_aligned"() FROM PUBLIC;
--> statement-breakpoint
SELECT "audit"."assert_partitions_aligned"();
--> statement-breakpoint
-- 2. ensure_partitions: new signature (adds the `from_month` test seam that simulates a run in a
--    later month), so the old overload is dropped and the new one revoked from PUBLIC again.
DROP FUNCTION "audit"."ensure_partitions"(integer);
--> statement-breakpoint
CREATE FUNCTION "audit"."ensure_partitions"(months_ahead integer, from_month date DEFAULT NULL)
RETURNS integer LANGUAGE plpgsql
  SET TimeZone = 'UTC' SET search_path = pg_catalog, audit AS $$
DECLARE
  -- UTC wall-clock month start as a timezone-less timestamp: arithmetic below cannot be shifted
  first_month timestamp := date_trunc('month', COALESCE(from_month::timestamp, now() AT TIME ZONE 'UTC'));
  created integer := 0;
  part_start timestamp;
  part_end timestamp;
  part_name text;
BEGIN
  IF months_ahead < 0 OR months_ahead > 24 THEN
    RAISE EXCEPTION 'months_ahead must be between 0 and 24';
  END IF;
  FOR i IN 0..months_ahead LOOP
    part_start := first_month + make_interval(months => i);
    part_end := first_month + make_interval(months => i + 1);
    part_name := format('events_y%sm%s', to_char(part_start, 'YYYY'), to_char(part_start, 'MM'));
    IF to_regclass(format('audit.%I', part_name)) IS NULL THEN
      EXECUTE format('CREATE TABLE audit.%I PARTITION OF audit.events FOR VALUES FROM (%L) TO (%L)',
        part_name, part_start AT TIME ZONE 'UTC', part_end AT TIME ZONE 'UTC');
      EXECUTE format('CREATE UNIQUE INDEX %I ON audit.%I (seq)', part_name || '_seq_uq', part_name);
      EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON audit.%I FOR EACH STATEMENT EXECUTE FUNCTION audit.reject_mutation()',
        part_name || '_no_truncate', part_name);
      created := created + 1;
    END IF;
  END LOOP;
  RETURN created;
END;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION "audit"."ensure_partitions"(integer, date) FROM PUBLIC;
--> statement-breakpoint
-- 3. future_partitions and reject_mutation: same bodies, now pinned (CREATE OR REPLACE keeps the
--    existing grants and trigger bindings; a test asserts it).
CREATE OR REPLACE FUNCTION "audit"."future_partitions"() RETURNS integer LANGUAGE sql STABLE
  SET TimeZone = 'UTC' SET search_path = pg_catalog, audit AS $$
  SELECT count(*)::integer
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'audit'
    AND c.relkind = 'r'
    AND c.relname ~ '^events_y[0-9]{4}m[0-9]{2}$'
    AND c.relname > 'events_y' || to_char(now() AT TIME ZONE 'UTC', 'YYYY') || 'm' || to_char(now() AT TIME ZONE 'UTC', 'MM');
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION "audit"."reject_mutation"() RETURNS trigger LANGUAGE plpgsql
  SET search_path = pg_catalog, audit AS $$
BEGIN
  RAISE EXCEPTION '% on %.% is not allowed: the audit log is append-only', TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME
    USING ERRCODE = 'insufficient_privilege';
END;
$$;
